server:
  session:
    timeout: 1800
  port: 9099

#spring相关
spring:
  application:
    name: user-manage-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/jdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      poolName: InstitutionHikariCP
      maximumPoolSize: 5
      minimumIdle: 3
      maxLifetime: 2000000
      connectionTimeout: 30000
      idleTimeout: 30000
      dataSourceProperties:
        # opt for mysql
        cachePrepStmts: true
        useServerPrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

logging:
  level:
    org.springframework.security: debug
    com.ibatis: debug
    com.zaxxer.hikari: debug